name: hemo_dialysis
description: "Hemo dialysis project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  timer_count_down: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/store/
    - lib/assets/process/


  fonts:
    - family: IranSans
      fonts:
        - asset: lib/assets/fonts/iran_sans.ttf
        - asset: lib/assets/fonts/iran_sans_ultra_light.ttf
          weight: 100
        - asset: lib/assets/fonts/iran_sans_light.ttf
          weight: 300
        - asset: lib/assets/fonts/iran_sans_medium.ttf
          weight: 500
        - asset: lib/assets/fonts/iran_sans_bold.ttf
          weight: 900

    - family: IranSansFaNum
      fonts:
        - asset: lib/assets/fonts/iran_sans.ttf
        - asset: lib/assets/fonts/iran_sans_fa_num_ultra_light.ttf
          weight: 100
        - asset: lib/assets/fonts/iran_sans_fa_num_light.ttf
          weight: 300
        - asset: lib/assets/fonts/iran_sans_fa_num_medium.ttf
          weight: 500
        - asset: lib/assets/fonts/iran_sans_fa_num_bold.ttf
          weight: 900
#        - asset: lib/assets/fonts/iran_sans_fa_num_medium.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700