import '../../../infrastructure/utils/constants.dart';
import '../model/store_item_view_model.dart';

class StorePageRepository {
  List<StoreItemViewModel> getStoreItems() => [
        StoreItemViewModel(
          id: 1,
          title: 'صافی دیالیز',
          image: Constants.dialysisFilterImage,
          company: 'محصول شرکت داروسازی رازی',
          hasDelivery: true,
          hasDiscount: true,
          price: '510,000',
          rate: 5,
          rateCount: 400,
          volume: 'سطح 26 متر مربع',
        ),
        StoreItemViewModel(
          id: 2,
          title: 'ست همودیالیز',
          image: Constants.cartridgeRemoveBag1Image,
          company: 'محصول شرکت آلمانی فرنسوسیز',
          hasDelivery: true,
          hasDiscount: false,
          price: '1,300,000',
          rate: 3.5,
          rateCount: 2,
        ),
        StoreItemViewModel(
          id: 3,
          title: 'محلول ضد عفونی',
          image: Constants.bicarbProduct1Image,
          company: 'محصول شرکت داروسازی رازی',
          hasDelivery: true,
          hasDiscount: true,
          price: '110,000',
          rate: 4.5,
          rateCount: 540,
          volume: 'حجم 4 لیتری',
        ),
        StoreItemViewModel(
          id: 4,
          title: 'ست همودیالیز',
          image: Constants.cartridgeRemoveBag3Image,
          company: 'محصول شرکت آلمانی فرنسوسیز',
          hasDelivery: false,
          hasDiscount: false,
          price: '1,300,000',
          rate: 2.5,
          rateCount: 12,
        ),
        StoreItemViewModel(
          id: 5,
          title: 'محلول ضد عفونی',
          image: Constants.bicarbProduct2Image,
          company: 'محصول شرکت داروسازی رازی',
          hasDelivery: true,
          hasDiscount: false,
          price: '110,000',
          rate: 4.5,
          rateCount: 540,
          volume: 'حجم 4 لیتری',
        ),
        StoreItemViewModel(
          id: 6,
          title: 'ست همودیالیز',
          image: Constants.cartridgeRemoveBag2Image,
          company: 'محصول شرکت آلمانی فرنسوسیز',
          hasDelivery: false,
          hasDiscount: true,
          price: '1,300,000',
          rate: 5,
          rateCount: 14,
        ),
      ];
}
